// vue-team/src/modules/stage/components/ErrorPage/index.tsx
import {defineComponent} from 'vue';
import {useRouter} from '@/Global';
import styles from './index.module.less';

const props = {
  message: {
    type: String,
    default: '(404) Not Found!',
  },
};

export default defineComponent({
  name: 'ErrorPage',
  props,
  setup(props) {
    const router = useRouter();
    const onBack = () => router.back(1, 'page');
    return () => {
      return (
        <div class={styles.root}>
          <div class="message">{props.message}</div>
          <div class="back" onClick={onBack}>
            返回
          </div>
        </div>
      );
    };
  },
});

// react-team/src/modules/stage/components/ErrorPage/index.tsx
import {FC, memo, useCallback} from 'react';
import {useRouter} from '@/Global';
import styles from './index.module.less';

export interface Props {
  message?: string;
}

const Component: FC<Props> = ({message = '(404) Not Found!'}) => {
  const router = useRouter();
  const onBack = useCallback(() => router.back(1, 'page'), [router]);
  return (
    <div className={styles.root}>
      <div className="message">{message}</div>
      <div className="back" onClick={onBack}>
        返回
      </div>
    </div>
  );
};

export default memo(Component);
