// react-team/src/modules/article/views/Detail/index.tsx
import {DocumentHead, Link, exportView} from '@elux/react-web';
import {ItemDetail} from '@react-team/article-model';
import {FC, memo} from 'react';
import styles from './index.module.less';

interface Props {
  itemDetail?: ItemDetail;
}

const Component: FC<Props> = ({itemDetail}) => {
  return (
    <div className={`${styles.root} g-page-content`}>
      <DocumentHead title={itemDetail?.title || '......'} />
      <div className="hd">
        <Link className="back" to={1} action="back" target="window"></Link>
        <div className="title">{itemDetail?.title || '......'}</div>
        <div className="summary">{itemDetail?.summary || '......'}</div>
      </div>
      <div className="bd">{itemDetail?.content || ''}</div>
    </div>
  );
};

export default exportView(memo(Component));

// vue-team/src/modules/article/views/Detail/index.tsx
import {DocumentHead, Link, exportView} from '@elux/vue-web';
import {ItemDetail} from '@react-team/article-model';
import {PropType, defineComponent} from 'vue';
import styles from './index.module.less';

const props = {
  itemDetail: {
    type: Object as PropType<ItemDetail>,
  },
};

const Component = defineComponent({
  name: 'ArticleDetail',
  props,
  setup(props) {
    return () => (
      <div class={`${styles.root} g-page-content`}>
        <DocumentHead title={props.itemDetail?.title || '......'} />
        <div class="hd">
          <Link class="back" to={1} action="back" target="window"></Link>
          <div class="title">{props.itemDetail?.title || '......'}</div>
          <div class="summary">{props.itemDetail?.summary || '......'}</div>
        </div>
        <div class="bd">{props.itemDetail?.content || ''}</div>
      </div>
    );
  },
});

export default exportView(Component);
